### ISSUE TITLE
Compatibility with Python 3.8

### ISSUE THREAD

**Issue by YixuanSeanZhou** [grihabor/trino-query-parser#1]
## Summary

Currently, the package is not compatible with python 3.8. The problem seems to be the type hint, `Iterator[tuple[str, Callable]]` in `parser.py` is causing the issue.

**Comment by YixuanSeanZhou** [comment]
PR addressing this: https://github.com/grihabor/trino-query-parser/pull/2

**Comment by grihabor** [comment]
Nice, thank you!

**Comment by grihabor** [comment]
Related prs: https://github.com/grihabor/trino-query-parser/pull/3 https://github.com/grihabor/trino-query-parser/pull/4
